greeting:
  message: "hello"
quarkus:
  hibernate-orm:
    database:
      generation: "drop-and-create"
mp:
  messaging:
    outgoing:
      words-out:
        address: "words"
    incoming:
      words-in:
        address: "words"
